name: CI/CD Pipeline to AWS with Docker Hub

permissions:
  contents: write

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'README.md'

jobs:
  build-and-push:
    name: Build Docker Image, Push to Docker Hub
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: chrystjr2/chatfrontend
      IMAGE_TAG: dev-${{ github.run_number }}  
      
    steps:
      - name: Checkout code
        uses: actions/checkout@v3 

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
  
      - name: Build and push Docker image
        run: |
          docker build -t $IMAGE_NAME:$IMAGE_TAG .
          docker push $IMAGE_NAME:$IMAGE_TAG
      - name: Clone ArgoCD repository
        uses: actions/checkout@v3
        with:
          repository: rentdevops/argocd 
          token: ${{ secrets.CHECKOUT_TOKEN_NEW }}  
          path: awsdevops
          # ref: v2

      # - name: List files in the current directory
      #   run: |
      #     ls -la chatnode
      - name: Update ArgoCD deployment.yaml
        run: |
          sed -i "s|image: .*$|image: $IMAGE_NAME:$IMAGE_TAG|g" awsdevops/awsdevops/frontend.yaml
      - name: Commit and push changes to ArgoCD repo
        run: |
          cd awsdevops
          git config --global user.email "chriscrsov@gmail.com"
          git config --global user.name "chriscrsov"
          git add awsdevops/frontend.yaml  
          git commit -m "Update image tag to $IMAGE_TAG"
          git push
